[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.12"
tag_format = "$version"
bump_message = "bump: Semantic Release Bot: Release Version: $new_version ðŸ¤–ðŸš€ [skip ci]"
version_files = [
    "setup.py:version",
    "pyproject.toml:version"
]